### ISSUE TITLE
allow to skip some time at start 

### ISSUE THREAD

**Issue by matkoniecz** [benfred/py-spy#118]
Current flame generation graph starts as soon as program starts.

If one is not interested at all in profiling startup operations it may be tricky to exclude them

See for example case below where segment on the left is not easy to exclude.

Also, such unwanted parts mess up percent info making before/after comparisons harder.

I propose to add

```
    -s --skip <duration>        The number of seconds after startup when flame graph data is not sampled.
```

to

```
OPTIONS:
    -d, --duration <duration>    The number of seconds to sample for when generating a flame graph [default: 2]
    -f, --flame <flamefile>      Generate a flame graph and write to a file
    -p, --pid <pid>              PID of a running python program to spy on
    -r, --rate <rate>            The number of samples to collect per second [default: 100]

```

![Selection_002](https://user-images.githubusercontent.com/899988/59470662-b7888100-8e38-11e9-84f4-a34851c9cbaa.png)

**Comment by benfred** [comment]
I totally agree that excluding some startup operations is useful workflow - but I'm not really sure about adding commandline flags for it.

I have a draft of some changes here that you should check out ```pip install py-spy==0.2.0.dev1``` and this shows more how I'm thinking about letting users customize selecting the time . Running this release with the '--serve' option will bring up an embedded webserver where you can drag to select a time range:

<img width="1085" alt="Screen Shot 2019-06-29 at 9 20 21 PM" src="https://user-images.githubusercontent.com/69536/60392263-e0a14680-9ab3-11e9-97c0-ec980ccc7a1b.png">

I'm planning on adding an option to save a shareable flame graph (and other file formats) for the currently selected view - so that you can achieve the same result here.

**Comment by matkoniecz** [comment]
> drag to select a time range

That is likely to be significantly more powerful than mix of command line options!

**Comment by weixingsun** [comment]
Why not just adding a single cmd flag , and give the option to user ?

**Comment by matkoniecz** [comment]
> Running this release with the '--serve' option will bring up an embedded webserver where you can drag to select a time range:

Is it still necessary to install this specific version? I am unable to track it down in `py-spy --help` or in readme
