### ISSUE TITLE
Upload source to pypi

### ISSUE THREAD

**Issue by DD5HT** [benfred/py-spy#151]
Would it be possible to upload the source files to pipy too? So it would be possible for other setups to build the wheels from source.

**Comment by benfred** [comment]
What other setup are you interested in?

The only supported platforms that don't have binary wheels on pypi are freebsd and arm - and it's should be much easier just to grab a precompiled binary for those from the [releases](https://github.com/benfred/py-spy/releases) page than to compile this yourself.

I'm a little wary of providing a source package on pypi - mainly because this is actually a rust project and will fail to build if you don't have a rust compiler installed. Most python programmers won't have a rust compiler, and if you do have a rust compiler you can go ```cargo install py-spy``` to build from source.

**Comment by DD5HT** [comment]
The main setup would be to build our own internal wheels for the package. Currently we use the sources on devpi for that.  It is also quite common for C packages to have the source available on the devpi. Since most people won't probably compile the package from source I don't see a big problem in adding the source.

**Comment by benfred** [comment]
For your use case, you should be able to get the source directly from github. Like to build a wheel for the most recent stable version is just:

```
pip wheel git+https://github.com/benfred/py-spy.git@v0.1.11
```
