### ISSUE TITLE
Error when running record example

### ISSUE THREAD

**Issue by bergercookie** [benfred/py-spy#170]
I've installed `py-spy` using the latest cargo nightly version - `cargo install py-spy` (0.1.11).

I want to run the record example providing the python executable:

`py-spy record a.svg  -- python3 ./hello-world.py`

I'm getting the following output:

```
error: Found argument '-o' which wasn't expected, or isn't valid in this context
USAGE:
    py-spy [FLAGS] [OPTIONS] --pid <pid> [python_program]...
For more information try --help
```

What does work, is running py-spy without the record subcommand but that runs the `top` version instead of `record`.

`py-spy -- python3 ./hello-world.py`

**Comment by benfred** [comment]
The README on master is for v0.2.1, and the commandline usage has changed since v0.1.1 =(.  

I've updated crates.io with the 0.2.1 release, you should be able go ```cargo install py-spy``` to grab it now.

You can also see the README for v0.1.1 here: https://github.com/benfred/py-spy/tree/v0.1.1 . To generated a flamegraph in v0.1.1 is something like ```py-spy -o flame.svg -- python program.py```

**Comment by bergercookie** [comment]
Yup, downloading the new version from cargo as we speak.

Thanks!
