### ISSUE TITLE
Missing musl binary for 0.3.1

### ISSUE THREAD

**Issue by nicktimko** [benfred/py-spy#203]
I was looking at updating the version in my Alpine container, but noticed the one missing artifact from 0.3.0 to 0.3.1 was the `py-spy-v0.3.1-x86_64-unknown-linux-musl.tar.gz`. I know the release is still pretty fresh :green_salad: , but is the musl build planned?

Huge thanks for building and maintaining this tool combining the two best langs :smile:

**Comment by benfred** [comment]
Thanks! 

The github releases are automatically uploaded by travis/appveyor on a tagged release. The musl build failed because of a flaky integration test so it didn't upload on v0.3.1 =(

I restarted the build and the x86_64 musl artifact should be there be the for v0.3.1 now  (and I'll deal with the flaky test in a future change ... ).
