### ISSUE TITLE
Question: why are the same methods listed multiple times with varying line numbers?

### ISSUE THREAD

**Issue by madig** [benfred/py-spy#213]
It makes the left-heavy view confusing. Is it because of the sampling method, which just fetches the current line number?

I know about `-F`, but what if I have two classes in the same file with a method with the same name?

**Comment by benfred** [comment]
By default we're profiling at the line level rather than the function level - causing different lines of a function to appear as separate entries (unless you specify -F like you mentioned).

We don't have information about where the function starts right now to display function names like cProfile - we only have the function name and current line number.   Getting the starting line number of the function like cProfile does would involve parsing the python file . (cProfile is an instrumented profiler so can get the first line number easily, but py-spy is a sampling profile and doesn't get called automatically when every function starts).

**Comment by schmave** [comment]
I may be reading this wrong, but I think that first_lineno that you read in [get_line_number](https://github.com/benfred/py-spy/blob/e21c2ce629c23e1f75b2edf5ff25592a835cd562/src/stack_trace.rs#L155) is the first line of the function, which would provide a way to distinguish between multiple functions in the same file that have the same name. Would it be possible to add an option that reports time based on function name + first_lineno, or modify the existing `-F` option so that it includes first_lineno? 

pyinstrument is a sampling profiler that does a good job of combining stack traces from the same functions, and it looks like [they use co_firstlineno](https://github.com/joerick/pyinstrument/blob/master/pyinstrument/profiler.py#L80) for that purpose. 

I just learned about py-spy, and it's awesome! Thanks for making it.
