### ISSUE TITLE
Filter by function 

### ISSUE THREAD

**Issue by fgadaleta** [benfred/py-spy#239]
Would it be possible to profile a specific function, say a connect to SQL server or any `foo()` function in the module?

As a guide, I would want to profile 

```
import sqlite3
conn = sqlite3.connect('my_database.sqlite')
...
```

but for some reason I don't get nothing from that stack trace

I profile with the command below
`sudo RUST_LOG=info target/debug/py-spy dump --locals --pid 21123`

**Comment by benfred** [comment]
The 'dump' command just gives you a single stack trace at that point in time - it will only show the code that is running. I'm guessing the sqlite3 connection in this case is basically instant so you won't see it show up.

The flamegraph/speedscope code will let you drill down on to a specific function

**Comment by fgadaleta** [comment]
> The 'dump' command just gives you a single stack trace at that point in time - it will only show the code that is running. I'm guessing the sqlite3 connection in this case is basically instant so you won't see it show up.
> 
> The flamegraph/speedscope code will let you drill down on to a specific function

Do you mean `record` command?
I tried 

`sudo RUST_LOG=info target/debug/py-spy record -f flamegraph -o dump.svg -r 500 -s -F --pid 2563`

and the Python program as below:
```

def wait(secs: int):
    sleep(secs)


if __name__ == "__main__":
    print("Opened database successfully as PID=%s" % os.getpid())
    wait(20)

    print("Connecting to DB")
    conn = sqlite3.connect('my_database.sqlite')
    cursor = conn.cursor()
```

and the only thing I see is

![image](https://user-images.githubusercontent.com/11614447/81529423-1b743c00-935f-11ea-9e25-097051b722fe.png)

**Comment by benfred** [comment]
Yeah - I meant using the record option. With the flamegraph option you used there, you can 'search' in the top right text box to filter down to a specific function.

Note that py-spy is a sampling profiler, by default we sample 100 times a second and record a stacktrace of whats happening at each sample. In this case you will have ~2000 samples on the 'wait' call, and since the sqlite3 code is very fast you probably don't have any samples recorded in the sqlite code.

For very short-lived blocks of code, you can always run in a loop to figure out the relative time spent in each call:
```python
while True:
    conn = sqlite3.connect('my_database.sqlite')
    cursor = conn.cursor()
```
alternatively you can increase the sampling rate
