### ISSUE TITLE
Stance on understanding Python frameworks?

### ISSUE THREAD

**Issue by ormsbee** [benfred/py-spy#27]
How do you feel about py-spy having an understanding of some common Python frameworks? We have a fairly large Django project, and I wanted to experiment with being able to do things like, "Generate a flamegraph of this one particular view as it's invoked on a gunicorn worker in prod, and filter out all the other stuff." or "How much time are we spending in middleware processing?"

Does this sound like something that might one day be accepted as a pull request into this project, or do you feel it's inappropriate for the scope of py-spy? If it does sound like something that belongs in this project, can you give any pointers on how I should write things to increase the odds of it being accepted? I code Python for a living, but I'm very new to Rust.

Having been on the other side of this conversation many times, I realize that plugin interfaces can be tricky to nail down, so I'm perfectly happy with, "I haven't had time to think about it yet." I just wanted to check in before I started hacking around on it.

Thanks for making this great project!

**Comment by benfred** [comment]
I'm also pretty new to rust, this is my first real project written in it =). 

I'm not planning on any plugin support to py-spy, but I am planning on adding a Python API at some point.  The idea is to keep the commandline app written in rust, but then expose all the core functionality to Python using Pyo3. I've tested this out enough to make sure the approach will work and wrote up here: https://www.benfrederickson.com/writing-python-extensions-in-rust-using-pyo3/

Hopefully this will let you script the actions that you are interested in (like collect all the samples from the process, filter down to what you're interested in python and then use the filtered samples to generate a flamegraph or some such).

I'm also currently working on a better visualization tool for py-spy, so that you can hopefully accomplish most of what you're interested in here without having to write any code.

**Comment by ormsbee** [comment]
Thank you, that's really helpful to know.
