### ISSUE TITLE
Better flamegraph readability for deep call stacks

### ISSUE THREAD

**Issue by pzelasko** [benfred/py-spy#28]
When the call stacks are deep, the flamegraph annotations are becoming truncated and it's difficult (or impossible) to see which function took most time to execute. Perhaps you could introduce an option to trim the beginning of the function names, or generate a (much) higher resolution flamegraph?

Thanks!

**Comment by benfred** [comment]
The cool thing about the flame graphs is that they are interactive, you can zoom in by clicking on a function (so that it will take the whole screen) and you will get more details on hovering over with the mouse.  Does this help out at all?

Also, I'm working on some new visualization options that might help out here

**Comment by pzelasko** [comment]
Thanks a lot! I was opening it in Ubuntu's default image viewer, which is why I thought it's not interactive. It works a lot better in the browser. :+1:
