### ISSUE TITLE
Py-Spy vs Austin?

### ISSUE THREAD

**Issue by chrish42** [benfred/py-spy#292]
The README mentions the deprecated pyflame as the only other tool similar to Py-Spy. But there is also now Austin (https://github.com/P403n1x87/austin), which feels similar too. It might be interesting to mention a bit the pros and cons of Py-Spy vs. Austin the README.

**Comment by benfred** [comment]
Austin looks interesting, and I like the threaded output it uses in it's TUI. 

When I first wrote that section in the README- I thought it was important to mention pyflame and why py-spy was still worthwhile given that pyflame already existed and did something very similar.  I'm not super interested in maintaining a breakdown of py-spy vs each other profiler out there, so I just removed the line talking about pyflame in the most recent commit since pyflame is deprecated now.

Thanks!
