### ISSUE TITLE
py-spy GPL License

### ISSUE THREAD

**Issue by machine-mind** [benfred/py-spy#30]
Hi,
I really like the project. But I'm having concerns using it in our web application backend due to the GPL license of py-spy.

Are there any license issues using py-spy on our servers?

Best,
Stefan

**Comment by frankier** [comment]
The GPL doesn't transfer from software tools to software developed with them, otherwise, for example, everything written in Emacs would be liable to be released under the GPL. You can close this issue.

**Comment by benfred** [comment]
To second the response from @frankier, py-spy is an application rather than a library - you should feel free to use it on your servers.

 the GPL means that if you change the source code to py-spy and distribute a new version of py-spy then you need to distribute the source code of your changes to py-spy too. It doesn't apply at all to the source code to your web app.
