### ISSUE TITLE
Relax/remove `is_python_bin` requirement

### ISSUE THREAD

**Issue by kud1ing** [benfred/py-spy#34]
`py-spy` seems to work quite well for third-party binaries that embed CPython.
However `is_python_bin` requires that on Windows `\python` is in the path.

The path can not easily be changed, since this third-party software is installed via an installer.
What works is duplicating `third_party_path\foo.exe` as `third_party_path\python.exe`.

Would it be possible to relax/remove the `is_python_bin` requirement?

**Comment by NiklasRosenstein** [comment]
How did you get it working with a binary that embeds CPython?

I have an application here that I want to debug. It "embeds" CPython only via an additional dynamic library. Attaching py-spy to the process gives me "Couldn't find python binary".

**Comment by kud1ing** [comment]
`Couldn't find python binary` comes from the function `is_python_bin()` which checks that (on Windows) `\python` is in the executable path. So either change a directory to start with `python`, or rename the executable to `python`.

**Comment by benfred** [comment]
@NiklasRosenstein if you rename your application to python (or python.exe on windows) py-spy will probably work - it will load stuff up from the libpython dynamic library if it finds it.

@kud1ing I agree we should do better here - I think fixing this will also let us profile uwsgi too. Rather than matching the executable name (like python.exe etc), I'm thinking of trying to just figure out what the executable is and using that.

**Comment by NiklasRosenstein** [comment]
> if you rename your application to python (or python.exe on windows) py-spy will probably work - it will load stuff up from the libpython dynamic library if it finds it.

Awesome! Thanks for the quick reply. It would be nice if I wouldn't have to rename the application, and I guess that is what this issue is for. 😁

**Comment by NiklasRosenstein** [comment]
I can't get it to work on OSX by renaming -- I've tried renaming the binary inside `Content/MacOS` to `python`, updated the `Info.plist` so that the CFBundleName reads `python` and renamed the app to `python.app` -- none of it worked, nor in combination.

**Comment by kud1ing** [comment]
On Mac the logic is different: https://github.com/benfred/py-spy/blob/08b98715caab060aeb5d664775511a513e2d96d8/src/python_spy.rs#L354

**Comment by benfred** [comment]
For getting the executable path directly (rather than match filenames in the virtual memory maps like we are doing now), it seems like on linux this is doing using procfs (read the [/proc/PID/exe symlink](http://man7.org/linux/man-pages/man5/proc.5.html)), windows by calling [GetProcessImageFileNameW](https://docs.microsoft.com/en-us/windows/desktop/api/psapi/nf-psapi-getprocessimagefilenamew) function and on OSX by calling [proc_pidpath](https://astojanov.wordpress.com/2011/11/16/mac-os-x-resolve-absolute-path-using-process-pid/).  It shouldn't be too hard to do and probably will work better

**Comment by benfred** [comment]
That last commit should fix this

**Comment by benfred** [comment]
Fixed in 0.1.6 release

**Comment by kud1ing** [comment]
I've tested this successfully together with https://github.com/benfred/py-spy/commit/6c2706867f9c13a2e5f9f3acc6c9e47f890094e7
