### ISSUE TITLE
ThreadPoolExecutor pipeline based on add_done_callback: incomplete profile

### ISSUE THREAD

**Issue by Wenzel** [benfred/py-spy#392]
Hi,

I wanted to use py-spy to profile a pipeline I've built around ThreadPoolExecutor.
The pipeline has been created by piping the "stage" using futures and [`add_done_callback`](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Future.add_done_callback) function.

I created a repo to demonstrate the issue I'm facing:
https://github.com/Wenzel/bug_pyspy

Here is the pipeline implementation:
https://github.com/Wenzel/bug_pyspy/blob/master/test.py#L13

The idea of using py-spy here was to pinpoint why a given stage of the pipeline was slow, and pinpoint the performance issue.

However, when generating a speedscope profile, I get this:
![image](https://user-images.githubusercontent.com/964610/118038361-4d075500-b36f-11eb-8590-f6e42a6d1484.png)

Despite the fact that my pipeline has 2 stages, (both of them calling `slow_func()`) i can only see one stage in the profile.

Am i missing something here, or is there an issue with py-spy ?

Thank you !

**Comment by benfred** [comment]
How did you invoke py-spy? Also what operating system and version of python are you using?

By default py-spy tries to ignore traces from threads that are idle - since the 'time.sleep' function in your test program isn't consuming any CPU cycles, most of those stack traces will be ignored. I'd recommend trying this again with the ```--idle``` flag if you haven't included that already. 

When I ran your test program with the ```--idle``` flag set the output seems to make sense to me:

<img width="1778" alt="Screen Shot 2021-05-12 at 10 13 52 PM" src="https://user-images.githubusercontent.com/69536/118081375-15e57380-b370-11eb-87e9-8eca383a6f02.png">

**Comment by benfred** [comment]
Haven't heard back, so I'm closing this.  feel free to reopen if the problem is still occurring

**Comment by Wenzel** [comment]
Hi @benfred ,

sorry for my lack of feedback.
As you said, I think the flag `--idle` is what I was looking for !

Confirming that this issue is closed for me.

Thank you for maintaining py-psy o/
