### ISSUE TITLE
analyze dump

### ISSUE THREAD

**Issue by whyzdev** [benfred/py-spy#41]
As mentioned in the case #40, please consider add a feature to allow py-spy analyze dump files. 
Rather than use --pid pid or run live target process, add an argument for loading windows dump or core dump on linux/mac. Thanks!

**Comment by benfred** [comment]
this could be useful, but will only let you get a single stack trace (like the output you get from passing --dump on the command line) instead of something like flamegraphs.

fwiw, rbspy does testing like this - it grabs some core dumps and verifies that it can extract the correct stack trace from them, which is a pretty neat way of testing.

**Comment by kapilt** [comment]
i think this would be useful. i've been thinking about using py-spy to create a thread stack dump tool, it was a little unclear if that fit into the top like ux / goals of py-spy.

**Comment by benfred** [comment]
Ability to do this with Linux has been added with https://github.com/benfred/py-spy/pull/538  -
