### ISSUE TITLE
Analyse memory usage

### ISSUE THREAD

**Issue by diogobaeder** [benfred/py-spy#46]
Hi there,

First of all, great job! I managed to get this running with a project I develop, and it's pretty neat! :-)

So, I wanted to ask, is there any plan to include, in py-spy, the support to also display memory usage inside the "spied" processes as well? I've been trying memory dump libraries and it's been a PITA to deal with them, some of them work but they impose a high burden on the process in production, and I really need a reliable and robust way to investigate the memory usage of my project, so I thought this project could be a very good starting place to have a tool for this too - since it can attach to an already-running process, without slowing it down.

Thanks!
Diogo

**Comment by benfred** [comment]
Thanks!

Memory profiling would be cool, but it's not something I'm planning on implementing here. I think it would require very different techniques: instead of just reading the process memory, we'd have to instrument PyMem_Malloc and related functions to track how much memory is being allocated and what code is calling the malloc functions.  I can't see a way of doing this without slowing down the target process =(.

**Comment by 3tilley** [comment]
Hello, I thought I would come back to this thread rather than starting a new one. I love py-spy and the approach it takes, and on top of CPU profiling I'd love to be able to do memory snapshots.

From what I understand about profiling as well as your comments, I can imagine two approaches:
# Instrument the allocators to get a real-time memory usage
# Pause and scan the entire address space at occasional intervals. These could be time based or perhaps whenever memory thresholds were crossed

Do you have thoughts? Would it be cheap to attach process memory usage to each sample, so at least a plot of usage over time would be possible, and the functions where peak memory usage occurred were obvious?

I'm torn between wanting to keep to the spirit of py-spy being unintrusive, but wanting to reuse the infrastructure to provide more instrusive analytics for opt-in users.

**Comment by gatopeich** [comment]
Can't we just sample on memory events like Linux perf does?

**Comment by ankush** [comment]
Just sharing this here in case someone someone stumbles upon this thread: https://github.com/bloomberg/memray
