### ISSUE TITLE
Raspberry pi 3 version on PyPI

### ISSUE THREAD

**Issue by easysoft2k15** [benfred/py-spy#72]
It would be nice to have _Raspberry pi 3_ version on PyPI.
Thank You

**Comment by auscompgeek** [comment]
PyPI does not allow binary wheels for ARM.

**Comment by easysoft2k15** [comment]
Understood.
Thank You for the feedback.

**Comment by benfred** [comment]
PyPI doesn't support binary arm wheels yet (though I think support is being added for that).

There is a cool project ( [piwheels](https://www.piwheels.org/)) that aims to build raspberry pi wheels  for everything on pypi automatically:
https://bennuttall.com/piwheels-building-a-faster-python-package-repository-for-raspberry-pi-users/
 I don't think py-spy works yet, because we require a rust compiler to be installed. If we can get setup.py to install rust if it is missing this might work though

**Comment by benfred** [comment]
pypi supports arm binary wheels - and they are up on pypi now https://github.com/benfred/py-spy/issues/328
